cc_binary(
    name = "tutorial",
    srcs = [
        "tutorial.cpp",
        "http_trace_context.h",
        "3rd_party/httplib.h",
    ],
    tags = ["examples"],
    deps = [
        "//:pinpoint-cpp",
    ],
)

cc_binary(
    name = "http_server",
    srcs = [
        "http_server.cpp",
        "http_trace_context.h",
        "3rd_party/httplib.h",
    ],
    tags = ["examples"],
    deps = [
        "//:pinpoint-cpp",
    ],
)

cc_binary(
    name = "url_stat_test",
    srcs = [
        "url_stat_test.cpp",
        "3rd_party/httplib.h",
    ],
    tags = ["examples"],
    deps = [
        "//:pinpoint-cpp",
    ],
)
