version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pinpoint-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pinpoint123
      MYSQL_DATABASE: test
      MYSQL_USER: pinpoint
      MYSQL_PASSWORD: pinpoint123
    ports:
      - "3306:3306"
      - "33060:33060"  # X Protocol port
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppinpoint123"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

volumes:
  mysql_data:
